/*
 * a.java
 *
 * Created on __DATE__, __TIME__
 */

package modelview;

import java.util.Random;

import javax.swing.JOptionPane;

/**
 *
 * @author  __USER__
 */
public class Card2View extends javax.swing.JFrame {
	Map2SView m = new Map2SView();

	/** Creates new form a */
	public Card2View() {
		initComponents();
		jButton1.setOpaque(false);
		jButton2.setOpaque(false);
		jButton3.setOpaque(false);
		jButton4.setOpaque(false);
		this.setLocationRelativeTo(null);
		if (m.card1 == 1) {
			jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/images/card1.png")));
		}
		if (m.card1 == 2) {
			jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/images/card2.png")));
		}
		if (m.card1 == 3) {
			jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/images/card3.png")));
		}
		if (m.card2 == 1) {
			jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/images/card1.png")));
		}
		if (m.card2 == 2) {
			jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/images/card2.png")));
		}
		if (m.card2 == 3) {
			jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/images/card3.png")));
		}
		if (m.card3 == 1) {
			jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/images/card1.png")));
		}
		if (m.card3 == 2) {
			jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/images/card2.png")));
		}
		if (m.card3 == 3) {
			jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/images/card3.png")));
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		jPanel1.setLayout(null);

		jButton1.setBackground(new java.awt.Color(255, 255, 255));
		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img1/空白卡片.png"))); // NOI18N
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton1.setBorder(null);
		jPanel1.add(jButton1);
		jButton1.setBounds(130, 30, 140, 210);

		jButton2.setBackground(new java.awt.Color(255, 255, 255));
		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img1/空白卡片.png"))); // NOI18N
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jButton2.setBorder(null);
		jPanel1.add(jButton2);
		jButton2.setBounds(270, 30, 140, 210);

		jButton3.setBackground(new java.awt.Color(255, 255, 255));
		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img1/空白卡片.png"))); // NOI18N
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});
		jButton3.setBorder(null);
		jPanel1.add(jButton3);
		jButton3.setBounds(410, 30, 140, 210);

		jButton4.setBackground(new java.awt.Color(255, 255, 255));
		jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img1/×按钮.png"))); // NOI18N
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});
		jButton4.setBorder(null);
		jPanel1.add(jButton4);
		jButton4.setBounds(730, 0, 40, 40);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/img1/卡片界面.png"))); // NOI18N
		jPanel1.add(jLabel1);
		jLabel1.setBounds(0, 0, 770, 290);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 292,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		if (m.order == 1) {
			if (m.card3 == 1) {//加钱
				int res = JOptionPane.showConfirmDialog(null, "是否使用卡片", "使用卡片",
						JOptionPane.YES_NO_OPTION);
				if (res == JOptionPane.YES_OPTION) {
					m.m1 = m.m1 + 300;
					JOptionPane.showMessageDialog(null, "获得三百块钱", "使用卡片",
							JOptionPane.CANCEL_OPTION);
					jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/img1/空白卡片.png")));
					m.card3 = 0;
				} else {
					m.card3 = 1;
					return;
				}
			}
			if (m.card3 == 2) {//机遇
				int res = JOptionPane.showConfirmDialog(null, "是否使用卡片", "使用卡片",
						JOptionPane.YES_NO_OPTION);
				if (res == JOptionPane.YES_OPTION) {
					Random r1 = new Random();
					int sj1 = r1.nextInt(2);
					if (sj1 == 0) {
						m.s1 = 1;
						JOptionPane.showMessageDialog(null, "停止一回合", "随机事件",
								JOptionPane.CANCEL_OPTION);
					} else if (sj1 == 1) {
						m.m1 = m.m1 + 300;
						JOptionPane.showMessageDialog(null, "获得300文钱", "随机事件",
								JOptionPane.CANCEL_OPTION);
					} else if (sj1 == 2) {
						m.m1 = m.m1 - 100;
						JOptionPane.showMessageDialog(null, "减少100文钱", "随机事件",
								JOptionPane.CANCEL_OPTION);
					}
					jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/img1/空白卡片.png")));
					m.card3 = 0;
				} else {
					m.card3 = 2;
					return;
				}
			}
			if (m.card3 == 3) {
				int res = JOptionPane.showConfirmDialog(null, "是否使用卡片", "使用卡片",
						JOptionPane.YES_NO_OPTION);
				if (res == JOptionPane.YES_OPTION) {
					m.s1 = 0;
					JOptionPane.showMessageDialog(null, "使用成功", "使用卡片",
							JOptionPane.CANCEL_OPTION);
					jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/img1/空白卡片.png")));
					m.card3 = 0;
				} else {
					m.card3 = 3;
					return;
				}
			}

		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		if (m.order == 1) {
			if (m.card2 == 1) {//加钱
				int res = JOptionPane.showConfirmDialog(null, "是否使用卡片", "使用卡片",
						JOptionPane.YES_NO_OPTION);
				if (res == JOptionPane.YES_OPTION) {
					m.m1 = m.m1 + 300;
					JOptionPane.showMessageDialog(null, "获得三百块钱", "使用卡片",
							JOptionPane.CANCEL_OPTION);
					jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/img1/空白卡片.png")));
					m.card2 = 0;
				} else {
					m.card2 = 1;
					return;
				}
			}
			if (m.card2 == 2) {//机遇
				int res = JOptionPane.showConfirmDialog(null, "是否使用卡片", "使用卡片",
						JOptionPane.YES_NO_OPTION);
				if (res == JOptionPane.YES_OPTION) {
					Random r1 = new Random();
					int sj1 = r1.nextInt(2);
					if (sj1 == 0) {
						m.s1 = 1;
						JOptionPane.showMessageDialog(null, "停止一回合", "随机事件",
								JOptionPane.CANCEL_OPTION);
					} else if (sj1 == 1) {
						m.m1 = m.m1 + 300;
						JOptionPane.showMessageDialog(null, "获得300文钱", "随机事件",
								JOptionPane.CANCEL_OPTION);
					} else if (sj1 == 2) {
						m.m1 = m.m1 - 100;
						JOptionPane.showMessageDialog(null, "减少100文钱", "随机事件",
								JOptionPane.CANCEL_OPTION);
					}
					jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/img1/空白卡片.png")));
					m.card2 = 0;
				} else {
					m.card2 = 2;
					return;
				}
			}
			if (m.card2 == 3) {
				int res = JOptionPane.showConfirmDialog(null, "是否使用卡片", "使用卡片",
						JOptionPane.YES_NO_OPTION);
				if (res == JOptionPane.YES_OPTION) {
					m.s1 = 0;
					JOptionPane.showMessageDialog(null, "使用成功", "使用卡片",
							JOptionPane.CANCEL_OPTION);
					jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/img1/空白卡片.png")));
					m.card2 = 0;
				} else {
					m.card2 = 3;
					return;
				}
			}

		}
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.setVisible(false);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		if (m.order == 1) {
			if (m.card1 == 1) {//加钱
				int res = JOptionPane.showConfirmDialog(null, "是否使用卡片", "使用卡片",
						JOptionPane.YES_NO_OPTION);
				if (res == JOptionPane.YES_OPTION) {
					m.m1 = m.m1 + 300;
					JOptionPane.showMessageDialog(null, "获得三百块钱", "使用卡片",
							JOptionPane.CANCEL_OPTION);
					jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/img1/空白卡片.png")));
					m.card1 = 0;
				} else {
					m.card1 = 1;
					return;
				}
			}
			if (m.card1 == 2) {//机遇
				int res = JOptionPane.showConfirmDialog(null, "是否使用卡片", "使用卡片",
						JOptionPane.YES_NO_OPTION);
				if (res == JOptionPane.YES_OPTION) {
					Random r1 = new Random();
					int sj1 = r1.nextInt(2);
					if (sj1 == 0) {
						m.s1 = 1;
						JOptionPane.showMessageDialog(null, "停止一回合", "随机事件",
								JOptionPane.CANCEL_OPTION);
					} else if (sj1 == 1) {
						m.m1 = m.m1 + 300;
						JOptionPane.showMessageDialog(null, "获得300文钱", "随机事件",
								JOptionPane.CANCEL_OPTION);
					} else if (sj1 == 2) {
						m.m1 = m.m1 - 100;
						JOptionPane.showMessageDialog(null, "减少100文钱", "随机事件",
								JOptionPane.CANCEL_OPTION);
					}
					jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/img1/空白卡片.png")));
					m.card1 = 0;
				} else {
					m.card1 = 2;
					return;
				}
			}
			if (m.card1 == 3) {
				int res = JOptionPane.showConfirmDialog(null, "是否使用卡片", "使用卡片",
						JOptionPane.YES_NO_OPTION);
				if (res == JOptionPane.YES_OPTION) {
					m.s1 = 0;
					JOptionPane.showMessageDialog(null, "使用成功", "使用卡片",
							JOptionPane.CANCEL_OPTION);
					jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
					"/img1/空白卡片.png")));
					m.card1 = 0;
				} else {
					m.card1 = 3;
					return;
				}
			}

		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Card2View().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	// End of variables declaration//GEN-END:variables

}